name: Run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libu2f-udev \
            libvulkan1
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --no-sandbox --disable-setuid-sandbox
        env:
          PUPPETEER_DISABLE_SANDBOX: 'true'
          PUPPETEER_ARGS: '--no-sandbox --disable-setuid-sandbox'
